### PR TITLE
Run tests for Mac target.

### PR DESCRIPTION
**Pull request by lukewar**
- us `NSHomeDirectory()` for OSX tests
- rename tests Info.plist
- add `TorTests-Mac` target and link it with `Tor-Mac` target
- link `TorTests-iOS` target with `Tor-iOS`

### CODE REVIEW

**Comment by lukewar** [comment]
Travis complains that `.travis.yml` is missing. But I have seen that there is separate branch with travis integration. Is it separated on purpose?

**Comment by conradev** [comment]
The `travis` branch is separated until it builds correctly, and then I will merge it. Right now it contains all of your changes and more, in an effort to get CI to work.

The logs are impossible to parse.

**Comment by lukewar** [comment]
I have no idea why it fails to integrate it.

**Comment by conradev** [comment]
Closing this because the `travis` branch is merged now 😄

**Pull request closed without merging**
